apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ServiceBusIssue.fullname" . }}-receiver
  labels:
    app.kubernetes.io/name: {{ include "ServiceBusIssue.name" . }}-receiver
    helm.sh/chart: {{ include "ServiceBusIssue.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.receiver.replica.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ServiceBusIssue.name" . }}-receiver
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ServiceBusIssue.name" . }}-receiver
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.receiver.image.repository }}:{{ .Values.receiver.image.tag }}"
          imagePullPolicy: {{ .Values.receiver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SERVICEBUS__CONNECTIONSTRING
              value: "{{ .Values.servicebus.connectionString }}"
            - name: SERVICEBUS__QUEUENAME
              value: "{{ .Values.servicebus.queueName }}"
            - name: SERVICEBUS__PREFETCHCOUNT
              value: "{{ .Values.servicebus.prefetchCount }}"
            - name: SERVICEBUS__WORKERS
              value: "{{ .Values.servicebus.workers }}"
            - name: SERVICEBUS__MAXAUTORENEWSECONDS
              value: "{{ .Values.servicebus.maxAutoRenewSeconds }}"
            - name: SERVICEBUS__SIMULATEPROCESSINGMILLISECONDS
              value: "{{ .Values.servicebus.simulateProcessingMilliseconds }}"
            - name: RECEIVERSTATUS__REDISDATABASEHOSTNAME
              value: "{{ include "ServiceBusIssue.fullname" . }}-redis"
          resources:
            limits:
              cpu: 1400m
              memory: 512Mi
      initContainers:
        - name: "sysctl"
          image: "busybox:latest"
          resources:
            limits:
              cpu: "10m"
              memory: "8Mi"
            requests:
              cpu: "10m"
              memory: "8Mi"
          securityContext:
            privileged: true
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -o errexit
              set -o xtrace
 
              sysctl -w net.ipv4.tcp_keepalive_time=180
              sysctl -w net.ipv4.tcp_keepalive_intvl=180
              sysctl -w net.ipv4.tcp_keepalive_probes=4
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ include "ServiceBusIssue.name" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
